#!/usr/bin/env node
// Publish-correctness guard (PreToolUse hook — wired in .claude/settings.json).
// Enforces the mechanically-decidable subset of the AGENTS.md "NEVER (publish-correctness)"
// list: the cases that are decidable without false positives AND most vital the agent never do.
// The AGENTS.md list stays the primary, preventive layer; this hook is the after-the-fact net.
//
// Contract: reads the tool call as JSON on stdin; exit 0 = allow, exit 2 = block (stderr is
// shown to the agent). Fails OPEN on any error — a buggy guard must never brick the agent.
// Generic: no project literals (paths are stock boilerplate).

import { readFileSync } from 'node:fs';

function block(reason) {
  process.stderr.write(`BLOCKED (AGENTS.md NEVER list): ${reason}\n`);
  process.exit(2);
}

let payload = {};
try {
  payload = JSON.parse(readFileSync(0, 'utf8') || '{}');
} catch {
  process.exit(0); // no/bad stdin → allow
}

const tool = payload.tool_name || '';
const input = payload.tool_input || {};
const filePath = String(input.file_path || '').replace(/\\/g, '/');
const content = String(input.content ?? input.new_string ?? '');
const isEdit = /Edit|Write/.test(tool);

// 1. Never edit upstream lib files — overwritten on the next lib update.
if (isEdit && /(^|\/)scripts\/(aem|lib-franklin)\.js$/.test(filePath)) {
  block('scripts/aem.js is upstream-managed and is overwritten on the next lib update. '
    + 'Put customizations in scripts/scripts.js instead.');
}

// 2. Never write content/*.plain.html directly — it is generated by the import script.
//    Exception: content/styleguide/** are net-new authored reference pages (no source import).
if (tool === 'Write' && /(^|\/)content\/.*\.plain\.html$/.test(filePath)
    && !/(^|\/)content\/styleguide\//.test(filePath)) {
  block('content/*.plain.html is generated — never write it directly; go through the import '
    + 'script. (Edits to .plain.html are temporary; the import script is the truth. '
    + 'The only exception is content/styleguide/ — net-new authored reference pages.)');
}

// 3. Never put a /content/ path in head.html nav/footer meta — EDS serves at the site root.
if (isEdit && /(^|\/)head\.html$/.test(filePath)
    && /<meta[^>]+name=["'](nav|footer)["'][^>]*content=["'][^"']*\/content\//i.test(content)) {
  block('head.html nav/footer meta points at /content/… — EDS serves content at the site root, '
    + 'so this 404s in production. Remove the meta (root default) or use /nav and /footer.');
}

// 4. Never run git / publish — the user does it via the Console UI.
if (tool === 'Bash') {
  const cmd = String(input.command || '');
  if (/(^|[\s;&|(])git(\s|$)/.test(cmd)) {
    block('Never run git — the user commits/pushes via the Console UI.');
  }
  if (/\b(aem|hlx)\b[^\n]*\bpublish\b/i.test(cmd)) {
    block('Never publish from the agent — the user publishes via the Console UI.');
  }
}

process.exit(0);
